# Generated by Django 4.2.6 on 2024-02-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_sub_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.IntegerField()),
                ('cprice', models.IntegerField()),
                ('cimage', models.FileField(upload_to='images/')),
                ('cname', models.CharField(max_length=200)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_manager.product_mst')),
            ],
        ),
    ]
